### PR TITLE
Add collection exists precondition

### PR DESCRIPTION
**Pull request by GoodbyePlanet**
Summary:

* For our migration changelog to work we need collections exists precondition, so here is the PR for it.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1966) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by GoodbyePlanet** [comment]
@alexandru-slobodcicov @r2liquibase Hi guys, do I need to first create an issue and then PR? 
Or if that is not the case can you review this PR?

**Comment by dagutten** [comment]
Hi,

What's the status of this PR? I really need this feature.

**Comment by alexandru-slobodcicov** [comment]
Hi @GoodbyePlanet, @dagutten added Test, squashed, commits and will merge

**Comment by GoodbyePlanet** [comment]
> Hi @GoodbyePlanet, @dagutten added Test, squashed, commits and will merge

Thanks :)

**Pull request merged**
